### ISSUE TITLE
Add multi column support

### ISSUE THREAD

**Issue by evening** [evening/expiration-tracker#17]
For now we could hard code it to 3. We would need to have multiple states i.e.:
```
  const { as, setas } = useStickyState('a')
  const { bs, setbs } = useStickyState('b')
  const { cs, setcs } = useStickyState('c')
```

might be good to have a general template / website style set up before doing so

**Comment by joseph-belmonte** [comment]
#28 but did not use three pieces of state and instead filtered the one list of entries based on the new location property on each entry.
