### ISSUE TITLE
Add field validation

### ISSUE THREAD

**Issue by evening** [evening/expiration-tracker#2]
1. Make sure there's a name, and maybe make sure it's unique
2. Make sure dates can never be null

**Comment by joseph-belmonte** [comment]
was there an issue with StickyState that required the use of null as a permissible type for the expiration date?

**Comment by evening** [comment]
hm do you think this is worth doing actually? maybe it's fine if the user has entries with the same name and no dates. i imagine instead of `expiration-tracker` it could be `food-tracker`, or something

**Comment by joseph-belmonte** [comment]
Yes, that's a good idea, you can easily have more than one of the same item in the fridge, pantry, etc. maybe including a suggestion instead with something like "That's already in the list, are you sure you want to add it again?" especially since we are not including quantities at the moment.
