### ISSUE TITLE
fix issues with grid layout

### ISSUE THREAD

**Issue by evening** [evening/expiration-tracker#25]
imo each category should overflow to next row, something like
```
fridge
[ item ] [expiration] [status] [action]
freezer
[ item ] [expiration] [status] [action]
pantry
[ item ] [expiration] [status] [action]
```
instead of everything in the same row

![image](https://user-images.githubusercontent.com/39542044/217668102-9508290c-ea24-4068-abc3-e30445c2c814.png)

**Comment by joseph-belmonte** [comment]
See #28 . It should revert to rows on smaller screens.
